export enum ACTIVE_TYPE {
    ADD_MESSAGE = 'ADD-MESSAGE',
    UPDATE_POST_TEXT = 'UPDATE-POST-TEXT',
    ADD_POST = 'ADD-POST',
    UPDATE_MESSAGE_TEXT = 'UPDATE-MESSAGE-TEXT',
    UPDATE_COUNTER_LIKE = 'UPDATE-COUNTER-LIKE'
}
